### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-AntonellaM#1]
Super buen trabajo @AntonellaM !!

Algunas pistas para mejorarlo:

- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by AntonellaM** [comment]
Gracias @nasivuela !
Ya están todos los puntos resueltos, incluyendo las mejoras de la 1 a la 5.
Seguro que hay cosas mejorables... ¡dímelo y me pongo a ello! :)

**Comment by nasivuela** [comment]
Super buen trabajo Antonella!

Cierro, pero te dejo un par de recomendaciones de ultima hora:
- En el componente Pokemon tienes un estado planteado que no se esta usando.
- En el componente App la lógica del método 'setFavorite' podría hacerse de manera más sencilla con un .map. Dale una intentona ;)

![](https://media.giphy.com/media/xT8qAY7e9If38xkrIY/giphy.gif)
